<div>
<img src="https://discuss.pytorch.org/uploads/default/original/2X/3/35226d9fbc661ced1c5d17e374638389178c3176.png" width="400" style="margin: 50px auto; display: block; position: relative; left: -30px;" />
</div>

<!--NAVIGATION-->
# | Basics | [Autograd >](2-Autograd.ipynb)

---

# Introduction

### Basics

In this first notebook, we will introduce Tensors, which are the base element in PyTorch.  
We will see different ways to create Tensors and check their properties. Then, we will briefly go through all the different kind of operations they support, such as mathematical operations, indexing, reshaping, expansion, masking, type conversion, etc.

### Table of Contents

#### 1. [Introduction](#Introduction)  
#### 2. [Tensor Creation](#Tensor-Creation)
#### 3. [Tensor Properties](#Tensor-Properties)  
#### 4. [Tensor Operations](#Tensor-Operations)  
#### 5. [Tensor Conversions](#Tensor-Conversions)  

### What is PyTorch ?
Python-based scientific computing library, similar to NumPy.  
Differentiates from NumPy in 3 main aspects:
- It allows to use the power of **GPU** computing
- It comes with an **automatic differentiation** module
- It is a fully-fledged **deep learning research platform**


In [1]:
import torch
import numpy as np

In [2]:
print("PyTorch Version:", torch.__version__)

PyTorch Version: 2.0.0+cpu


____

### What is a tensor?

A **matrix** is a grid of numbers, let's say (3x5).  
In simple terms, a **tensor** can be seen as a generalization of a matrix to higher dimension.  
It can be of arbitrary shape, e.g. (3 x 6 x 2 x 10). 

You can think of tensors as multidimensional arrays.

In [36]:
X = torch.tensor([1, 2, 3, 4, 5])
X
# X.dim()

tensor([1, 2, 3, 4, 5])

In [4]:
X.shape

torch.Size([5])

In [5]:
X = torch.tensor([[1, 2, 3], [4, 5, 6]])
X

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
X.shape

torch.Size([2, 3])

### PyTorch vs NumPy 

`torch.tensor` behaves like `numpy.array` under mathematical operations.  
The syntax is very similar between the two libraries.  
If you are familiar with NumPy, you can [browse here](https://github.com/wkentaro/pytorch-for-numpy-users#types) to check what are NumPy functions equivalent in PyTorch.

For example:

In [7]:
np.eye (2)

array([[1., 0.],
       [0., 1.]])

In [8]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [9]:
np.arange(1,5)

array([1, 2, 3, 4])

In [10]:
torch.arange(1,5)

tensor([1, 2, 3, 4])

As we said, `torch.tensor` additionally keeps track of the computation graphs (see next notebook) and provides GPU support.

---

# Tensor Creation

In [11]:
torch.zeros(5)

tensor([0., 0., 0., 0., 0.])

In [12]:
torch.ones(5)

tensor([1., 1., 1., 1., 1.])

In [15]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [16]:
torch.empty((3, 5))

tensor([[9.2755e-39, 1.0561e-38, 9.2755e-39, 9.5510e-39, 9.6429e-39],
        [4.2246e-39, 1.0286e-38, 1.0653e-38, 1.0194e-38, 8.4490e-39],
        [1.0469e-38, 9.3674e-39, 9.9184e-39, 8.7245e-39, 9.2755e-39]])

In [17]:
torch.rand((5, 3))

tensor([[0.7361, 0.7793, 0.2603],
        [0.0933, 0.5223, 0.0893],
        [0.3587, 0.3592, 0.2323],
        [0.8325, 0.9118, 0.8488],
        [0.5101, 0.7022, 0.6786]])

In [18]:
torch.arange(3, 9, 2)

tensor([3, 5, 7])

In [21]:
torch.linspace(0, 1, 11)

tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000])

In [25]:
A = torch.ones((2,3))
torch.zeros_like(A)
# torch.ones((2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

This list is not exhaustive but gives you an idea of the diversity of way to create a Tensor

<div style="background-color:lightblue;padding:1rem;border-radius: 0.015rem 0.015rem 0.03rem 0.03rem;">
<h3 style="display: inline; font-weight:bold">Your turn!</h3>
</div>

**_Create the tensor:_**

$$ \begin{bmatrix}
5 & 7 & 9 & 11 & 13 & 15 & 17 & 19
\end{bmatrix}  $$

In [38]:
# YOUR TURN
# torch.linspace(5,19,8)
torch.arange(5,21,2)

tensor([ 5,  7,  9, 11, 13, 15, 17, 19])

<div style="background-color:lightblue;padding:1rem;border-radius: 0.03rem 0.03rem 0.015rem 0.015rem;">
<h3 style="display: inline"></h3>
</div>

---

# Tensor Properties

In [39]:
x = torch.Tensor([[0,1,2], [3,4,5],[5,6,7]])

print("x.shape: \n%s\n" % (x.shape,))
print("x.size(): \n%s\n" % (x.size(),))
print("x.size(0): \n%s\n" % x.size(0))
print("x.size(1): \n%s\n" % x.size(1))
print("x.dim(): \n%s\n" % x.dim())
print("x.numel(): \n%s\n" % x.numel())

x.shape: 
torch.Size([3, 3])

x.size(): 
torch.Size([3, 3])

x.size(0): 
3

x.size(1): 
3

x.dim(): 
2

x.numel(): 
9


In [40]:
print("x.dtype: \n%s\n" % x.dtype)
print("x.device: \n%s\n" % x.device)

x.dtype: 
torch.float32

x.device: 
cpu


The `nonzero` function returns indices of the non zero elements.

In [43]:
x = torch.Tensor([[0,1,2], [3,4,5]])

print("x.nonzero(): \n%s\n" % x.nonzero())

x.nonzero(): 
tensor([[0, 1],
        [0, 2],
        [1, 0],
        [1, 1],
        [1, 2]])


---

# Tensor Operations

Unlike in NumPy, there are two ways to performs most operations in PyTorch:
 - using **`torch.op(tensor)`**
 - using **`tensor.op()`**

In [50]:
X = torch.rand(3, 2)
X

tensor([[0.8954, 0.0781],
        [0.4101, 0.6062],
        [0.3438, 0.3483]])

In [51]:
torch.exp(X)

tensor([[2.4484, 1.0813],
        [1.5069, 1.8334],
        [1.4103, 1.4167]])

In [52]:
X.exp()

tensor([[2.4484, 1.0813],
        [1.5069, 1.8334],
        [1.4103, 1.4167]])

You can easily chain operators :

In [53]:
X.sqrt().std()

tensor(0.2228)

In [55]:
X.sqrt().std(dim=1) # 第2维度 按照行[0.8954, 0.0781],[0.4101, 0.6062], [0.3438, 0.3483] 来求

tensor([0.4714, 0.0977, 0.0027])

In [56]:
(X.exp() + 2).sqrt() - 2 * X.log().sigmoid()  # be creative :-)

tensor([[1.1643, 1.6104],
        [1.2910, 1.2031],
        [1.3350, 1.3318]])

Many more functions are available: sin, cos, tanh, bmm, cumsum, dot, etc.

<div style="background-color:lightblue;padding:1rem;border-radius: 0.015rem 0.015rem 0.03rem 0.03rem;">
<h3 style="display: inline; font-weight:bold">Your turn!</h3>
</div>

Compute the norms of the row-vectors in matrix **X** without using `torch.norm()`.

Remember: $$||\vec{v}||_2 = \sqrt{x_1^2 + x_2^2 + \dots + x_n^2}$$

Hint: `X**2` computes the element-wise square.

In [64]:
# X = torch.arange(2,10,4)
X = torch.randn(2,3)
X_squared = X ** 2
R_sums = X_squared.sum(dim=1)
R_norms = R_sums.sqrt()
print("Rows norms:", R_norms)

Rows norms: tensor([0.6753, 1.5669])


In [84]:
X = torch.eye(4) + torch.arange(4).repeat(4, 1).float()
X
# YOUR TURN

# SOLUTION: tensor([3.8730, 4.1231, 4.3589, 4.5826])

tensor([[1., 1., 2., 3.],
        [0., 2., 2., 3.],
        [0., 1., 3., 3.],
        [0., 1., 2., 4.]])

In [83]:
# X = torch.arange(2,8,2)
X = torch.arange(5).repeat(4,1).float()
X

tensor([[0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.]])

<div style="background-color:lightblue;padding:1rem;border-radius: 0.03rem 0.03rem 0.015rem 0.015rem;">
<h3 style="display: inline"></h3>
</div>

## Reductions

In [85]:
X = torch.rand(3, 2)
X

tensor([[0.7626, 0.8068],
        [0.9445, 0.9549],
        [0.4307, 0.7938]])

In [86]:
X.sum()

tensor(4.6934)

In [87]:
X.max()

tensor(0.9549)

In [90]:
X.mean(dim=1)
X

tensor([[0.7626, 0.8068],
        [0.9445, 0.9549],
        [0.4307, 0.7938]])

In [91]:
X.norm(p=1)

tensor(4.6934)

In [97]:
X.norm(p=2,dim=1)

tensor([1.1102, 1.3431, 0.9032])

<div style="background-color:lightblue;padding:1rem;border-radius: 0.015rem 0.015rem 0.03rem 0.03rem;">
<h3 style="display: inline; font-weight:bold">Your turn!</h3>
</div>

For $X_{i,j}$ , compute $Y$ such that $Y_j = \log \big[ \sum_j \exp (X_{i,j}) \big]$.

In [98]:
X = torch.eye(4) + torch.arange(4).repeat(4, 1).float()

# YOUR TURN

# SOLUTION: tensor([3.4938, 3.5797, 3.7817, 4.1852])

<div style="background-color:lightblue;padding:1rem;border-radius: 0.03rem 0.03rem 0.015rem 0.015rem;">
<h3 style="display: inline"></h3>
</div>

## Linear Algebra

In [99]:
Y = torch.rand(2, 3)

In [101]:
# Matrix multiplication
Y.t() @ Y

tensor([[1.0673, 0.2288, 0.1703],
        [0.2288, 0.2170, 0.1922],
        [0.1703, 0.1922, 0.1714]])

In [103]:
Y.t().matmul(Y)

tensor([[1.0673, 0.2288, 0.1703],
        [0.2288, 0.2170, 0.1922],
        [0.1703, 0.1922, 0.1714]])

In [104]:
# CAUTION: Operator '*' does element-wise multiplication, just like in numpy!
# Y.t() * Y  # error, dimensions do not match for element-wise multiplication

In [106]:
torch.inverse(Y.t() @ Y)

tensor([[   102723.8125,  -2433174.0000,   2625566.0000],
        [ -2433174.2500,  57634168.0000, -62191344.0000],
        [  2625566.0000, -62191344.0000,  67108864.0000]])

In [110]:
Y = torch.rand(3, 3)

In [111]:
Y.det() # determinant

tensor(0.1418)

In [118]:
# Y.eig()
# Y.linalg.eig()
torch.linalg.eig(Y) # eigenvalues and eigenvectors

torch.return_types.linalg_eig(
eigenvalues=tensor([ 2.1355+0.j, -0.5016+0.j, -0.1324+0.j]),
eigenvectors=tensor([[-0.5050+0.j, -0.4711+0.j,  0.3953+0.j],
        [-0.6758+0.j, -0.2644+0.j, -0.7125+0.j],
        [-0.5369+0.j,  0.8415+0.j,  0.5797+0.j]]))

## In-place operators (mutations)

Functions that mutate the object end with an underscore, e.g. *add_*, *div_*, etc.

In [119]:
A = torch.eye(3)
A

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [120]:
A.add(5)

tensor([[6., 5., 5.],
        [5., 6., 5.],
        [5., 5., 6.]])

In [121]:
A 

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [122]:
A.add_(5)

tensor([[6., 5., 5.],
        [5., 6., 5.],
        [5., 5., 6.]])

In [ ]:
A

In [123]:
A.div_(3)

tensor([[2.0000, 1.6667, 1.6667],
        [1.6667, 2.0000, 1.6667],
        [1.6667, 1.6667, 2.0000]])

In [124]:
A

tensor([[2.0000, 1.6667, 1.6667],
        [1.6667, 2.0000, 1.6667],
        [1.6667, 1.6667, 2.0000]])

In [125]:
A.uniform_()  # fills the tensor with random uniform numbers in [0, 1]

tensor([[0.3765, 0.9563, 0.5972],
        [0.3140, 0.1772, 0.7899],
        [0.8895, 0.1876, 0.0497]])

In [126]:
A

tensor([[0.3765, 0.9563, 0.5972],
        [0.3140, 0.1772, 0.7899],
        [0.8895, 0.1876, 0.0497]])

In [131]:
B = torch.randn(2,3)
B

tensor([[-1.7457, -0.8798,  0.8985],
        [ 0.4566, -1.5843, -2.1525]])

In [134]:
B.max()

tensor(0.8985)

In [132]:
C = torch.tensor(B)
C

C:\Users\enhui\AppData\Local\Temp\ipykernel_7708\2311447644.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  C = torch.tensor(B)


tensor([[-1.7457, -0.8798,  0.8985],
        [ 0.4566, -1.5843, -2.1525]])

In [138]:
row_max = C.max(dim=1)
row_max

torch.return_types.max(
values=tensor([0.8985, 0.4566]),
indices=tensor([2, 0]))

In [151]:
A = torch.ones(3)
A

tensor([1., 1., 1.])

#### Also note the difference:
```python
A = A + 1  # After this operation, A is a new variable and memory has been copied
A += 1     # After this operation, A stayed the same variable and memory has been changed in place
```

Compare the outputs:

In [153]:
A = torch.ones(2)
A_before = A
A = A + 1

print(A, A_before)

tensor([2., 2.]) tensor([1., 1.])


In [145]:
A

tensor([2., 2.])

In [154]:
A = torch.ones(2)

A_before = A
A += 1

print(A, A_before)

tensor([2., 2.]) tensor([2., 2.])


## Indexing

Again, it works just like in NumPy.

In [159]:
A = torch.randint(2200, (3, 3)) # 创建一个3x3的张量，元素是0到2199之间的随机整数
A

tensor([[2077,  943, 1185],
        [1150, 2190, 1672],
        [1922,  164,  217]])

In [160]:
A[0, 0]

tensor(2077)

In [161]:
A[2, 1]

tensor(164)

In [162]:
A[1]

tensor([1150, 2190, 1672])

In [163]:
A[:, 1]

tensor([ 943, 2190,  164])

In [164]:
A[:, 1:2], A[:, 1:2].shape # [1,2)

(tensor([[ 943],
         [2190],
         [ 164]]),
 torch.Size([3, 1]))

In [165]:
A[1:, :2]

tensor([[1150, 2190],
        [1922,  164]])

_Note: You can use `...` to mark any number of dimension_

<div style="background-color:lightblue;padding:1rem;border-radius: 0.015rem 0.015rem 0.03rem 0.03rem;">
<h3 style="display: inline; font-weight:bold">Your turn!</h3>
</div>

In [166]:
X = torch.arange(40).view(5,8)
X

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39]])

**_Extract this vector from the tensor X:_**

$ \begin{bmatrix}
17 & 19 & 21 & 23 \\
\end{bmatrix}  $


In [168]:
# YOUR TURN 1:8:2: This selects the elements from index 1 to index 7, with a step of 2, which corresponds to columns 1, 3, 5, and 7. The step of 2 ensures we skip every other column.
X[2,1:8:2]

tensor([17, 19, 21, 23])

<div style="background-color:lightblue;padding:1rem;border-radius: 0.015rem 0.015rem 0.03rem 0.03rem;">
<h3 style="display: inline; font-weight:bold"></h3>
</div>

## Reshaping & Expanding

**`view`** is the equivalent of `reshape` in NumPy, but `view` does not allocate new memory: the output tensor shares the same data!

The number of arguments of `view` will be the number of dimensions of the output tensor.

In [169]:
X = torch.tensor([1, 2, 3, 4, 5, 6])
X

tensor([1, 2, 3, 4, 5, 6])

In [170]:
Y = X.view(2, 3)  # view tensor X on 2 dimensions, with a size 2 on dimension 1 and a size 3 on dimension 2
Y

tensor([[1, 2, 3],
        [4, 5, 6]])

In [172]:
Y = X.view(-1)  # -1 tells PyTorch to infer the number of elements along that dimension
Y, Y.shape

(tensor([1, 2, 3, 4, 5, 6]), torch.Size([6]))

In [174]:
Y = X.view(-1, 2) # -1 自动计算行数大小， 2 设为2列
Y, Y.shape

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 torch.Size([3, 2]))

**`expand`** creates a new view of the tensor with dimensions of size 1 expanded to a larger size. This does not allocate new memory either !

In [175]:
Y = torch.ones(5)
Y, Y.shape

(tensor([1., 1., 1., 1., 1.]), torch.Size([5]))

In [176]:
Y = Y.view(-1, 1)
Y, Y.shape

(tensor([[1.],
         [1.],
         [1.],
         [1.],
         [1.]]),
 torch.Size([5, 1]))

In [183]:
Y.expand(5, 5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [184]:
Y= torch.randn(2,3)
Y


tensor([[ 0.6716,  0.9204, -1.5056],
        [ 1.3430,  1.6325, -0.5413]])

In [193]:
Y = Y.view(-1)
Y.expand(4,6) # expand() 只能在维度大小为 1 或原始张量的某些维度可以广播的情况下使用。


tensor([[ 0.6716,  0.9204, -1.5056,  1.3430,  1.6325, -0.5413],
        [ 0.6716,  0.9204, -1.5056,  1.3430,  1.6325, -0.5413],
        [ 0.6716,  0.9204, -1.5056,  1.3430,  1.6325, -0.5413],
        [ 0.6716,  0.9204, -1.5056,  1.3430,  1.6325, -0.5413]])

In [194]:
X = torch.eye(4)
Y = X[3:, :]
Y, Y.shape

(tensor([[0., 0., 0., 1.]]), torch.Size([1, 4]))

`squeeze` and `unsqueeze`

In [196]:
Y = Y.squeeze()  # removes all dimensions of size '1'
Y, Y.shape

(tensor([0., 0., 0., 1.]), torch.Size([4]))

In [197]:
Y = Y.unsqueeze(1)  # add a new dimension in position 1
Y, Y.shape

(tensor([[0.],
         [0.],
         [0.],
         [1.]]),
 torch.Size([4, 1]))

_Note: There also exists `reshape` and `repeat` functions in PyTorch. They work similarly to `view` and `expand` but **do** copy memory_.

<div style="background-color:lightblue;padding:1rem;border-radius: 0.015rem 0.015rem 0.03rem 0.03rem;">
<h3 style="display: inline; font-weight:bold">Your turn!</h3>
</div>

**_Create the tensor:_**

$ \begin{bmatrix}
7 & 5 & 5 & 5 & 5 \\
5 & 7 & 5 & 5 & 5 \\
5 & 5 & 7 & 5 & 5 \\
5 & 5 & 5 & 7 & 5 \\
5 & 5 & 5 & 5 & 7 
\end{bmatrix}  $

Hint: You can use matrix sum and scalar multiplication

In [201]:
# YOUR TURN
X = torch.ones(5,5)*5 + torch.eye(5)*2
X

tensor([[7., 5., 5., 5., 5.],
        [5., 7., 5., 5., 5.],
        [5., 5., 7., 5., 5.],
        [5., 5., 5., 7., 5.],
        [5., 5., 5., 5., 7.]])

In [202]:
# 创建一个 5x5 的矩阵，初始值为 5
matrix = torch.full((5, 5), 5)

# 在对角线上填充 7
matrix.fill_diagonal_(7)

tensor([[7, 5, 5, 5, 5],
        [5, 7, 5, 5, 5],
        [5, 5, 7, 5, 5],
        [5, 5, 5, 7, 5],
        [5, 5, 5, 5, 7]])

**_Create the tensor:_**

$ \begin{bmatrix}
4 & 6 & 8 & 10 & 12 \\
14 & 16 & 18 & 20 & 22 \\
24 & 26 & 28 & 30 & 32
\end{bmatrix}$

In [204]:
# YOUR TURN
# 创建一个包含从 4 到 32 的数值，步长为 2 的 1D 张量
tensor = torch.arange(4, 33, 2)

# 将 1D 张量重塑为 3x5 的矩阵
tensor = tensor.view(3, 5)
tensor

tensor([[ 4,  6,  8, 10, 12],
        [14, 16, 18, 20, 22],
        [24, 26, 28, 30, 32]])

**_Create the tensor:_**

$ \begin{bmatrix}
2 & 2 & 2 & 2 & 2 \\
4 & 4 & 4 & 4 & 4 \\
6 & 6 & 6 & 6 & 6 \\
8 & 8 & 8 & 8 & 8
\end{bmatrix}  $

In [209]:
# YOUR TURN
# X = torch.arange(2,9,2).t()
X = torch.arange(2,9,2).view(4,1)
X.expand(4,5)

tensor([[2, 2, 2, 2, 2],
        [4, 4, 4, 4, 4],
        [6, 6, 6, 6, 6],
        [8, 8, 8, 8, 8]])

In [211]:
# 创建一个 1D 张量，包含 [2, 4, 6, 8]
tensor = torch.arange(2, 10, 2)

# 重复每个元素 5 次，得到形状为 (4, 5) 的矩阵
tensor = tensor.repeat(5, 1).t()
tensor

tensor([[2, 2, 2, 2, 2],
        [4, 4, 4, 4, 4],
        [6, 6, 6, 6, 6],
        [8, 8, 8, 8, 8]])

<div style="background-color:lightblue;padding:1rem;border-radius: 0.015rem 0.015rem 0.03rem 0.03rem;">
<h3 style="display: inline; font-weight:bold"></h3>
</div>

## Masking

In [212]:
X = torch.randint(100, (5, 3))
X

tensor([[83, 11, 98],
        [46, 35, 29],
        [58, 75, 49],
        [30, 85,  4],
        [64, 40, 66]])

In [218]:
# X[mask] 是一个 索引操作，它返回的是符合条件的元素，而不是修改矩阵。如果你想修改矩阵中的元素，应该直接进行赋值操作，例如 X[mask] = new_value。
mask = (X > 25) & (X < 75) 
mask

tensor([[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]])

In [219]:
X[mask]  # returns all elements matching the criteria in a 1D-tensor

tensor([], dtype=torch.int64)

In [221]:
# mask.sum() 计算的是 布尔掩码 (mask) 张量中 True 元素的数量。
mask.sum()  # number of elements that fulfill the condition

tensor(0)

In [222]:
(X == 25) | (X > 60)

tensor([[ True, False,  True],
        [False, False, False],
        [False,  True, False],
        [False,  True, False],
        [False, False, False]])

In [223]:
X[mask] = 0  # You can assign new values only to indices matching the condition:
X

tensor([[83, 11, 98],
        [ 0,  0,  0],
        [ 0, 75,  0],
        [ 0, 85,  4],
        [ 0,  0,  0]])

<div style="background-color:lightblue;padding:1rem;border-radius: 0.015rem 0.015rem 0.03rem 0.03rem;">
<h3 style="display: inline; font-weight:bold">Your turn!</h3>
</div>

In [224]:
X = torch.tensor([[1, 0, 2], [4, 6, 0]])

Get the number of non-zeros in **X**

In [225]:
# YOUR TURN
mask = X!=0
mask.sum()

tensor(4)

Compute the sum of all entries in **X** that are larger than the mean of all values in **X**.

In [235]:
# YOUR TURN
print(X.float().mean())
mask = X > X.float().mean()
mask.sum()

tensor(2.1667)


tensor(2)

Clip _(limit)_ all values of **X** between 0 and 3

In [241]:
# YOUR TURN
mask = (X <= 0) | (X >= 3)
X[mask] = 0
X

tensor([[1, 0, 2],
        [0, 0, 0]])

In [243]:

# 用于将张量的元素值限制在给定的范围内（即“裁剪”值）。它会将张量中所有小于指定最小值的元素设置为最小值，将所有大于指定最大值的元素设置为最大值，其他元素保持不变。
X.clamp(1,3) # 会替换为最小值或最大值

tensor([[1, 1, 2],
        [1, 1, 1]])

<div style="background-color:lightblue;padding:1rem;border-radius: 0.015rem 0.015rem 0.03rem 0.03rem;">
<h3 style="display: inline; font-weight:bold"></h3>
</div>

## And many more ...

In [244]:
# press tab to autocomplete
# x.

---

# Tensor Conversions

## Type conversions

The easiest way to cast a Tensor to a different type is to use the `Tensor.to(type)` function.

In [251]:
Y = 4 * torch.rand((2,4))

In [252]:
Y.dtype

torch.float32

In [253]:
Y.to(torch.float16)

tensor([[0.4409, 3.0586, 1.5166, 2.3223],
        [3.9980, 3.8906, 0.7378, 0.3477]], dtype=torch.float16)

In [257]:
Y.to(torch.int64)

tensor([[1, 0, 3, 2],
        [1, 2, 2, 2]])

In [258]:
#Y = torch.tensor([[1, 0, 3, 2], [1, 2, 2, 2]])

Y.to(torch.bool)

tensor([[ True, False,  True,  True],
        [ True,  True,  True,  True]])

Note the automatic type promotion :

In [260]:
# 会自动进行类型转换，使得不同类型的张量能够进行操作。自动类型提升（Type Promotion）具体来说：
torch.LongTensor([1, 2]) + torch.FloatTensor([1.1, 2.2])

tensor([2.1000, 4.2000])

## Converting between PyTorch and NumPy

In [261]:
X = np.random.random((5,3))
X

array([[0.20061144, 0.20142997, 0.50537475],
       [0.61191462, 0.67426279, 0.2583529 ],
       [0.20416085, 0.67493879, 0.89782829],
       [0.274782  , 0.86010627, 0.96175885],
       [0.51939046, 0.78995482, 0.22315873]])

In [262]:
# numpy ---> torch
Y = torch.from_numpy(X)  # Y is actually a DoubleTensor (i.e. 64-bit representation)
Y

tensor([[0.2006, 0.2014, 0.5054],
        [0.6119, 0.6743, 0.2584],
        [0.2042, 0.6749, 0.8978],
        [0.2748, 0.8601, 0.9618],
        [0.5194, 0.7900, 0.2232]], dtype=torch.float64)

In [263]:
Y = torch.rand((2,4))
Y

tensor([[0.4211, 0.6525, 0.5365, 0.0081],
        [0.5373, 0.7564, 0.2275, 0.8730]])

In [264]:
# torch ---> numpy
X = Y.numpy()
X

array([[0.4210863 , 0.65249944, 0.5365063 , 0.00805157],
       [0.53734726, 0.7564038 , 0.22753996, 0.8730477 ]], dtype=float32)

## Converting between GPU and CPU

First, you may want to check: 
 - that cuda can actually be used : `torch.cuda.is_available()`
 - how many gpus are available : `torch.cuda.device_count()`

In [265]:
torch.cuda.is_available()

False

In [266]:
torch.cuda.device_count()

0

In [267]:
x = torch.Tensor([[1,2,3], [4,5,6]])
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


### `torch.device`

The best way to easily move a tensor from a device to another is again by using the **`Tensor.to(...)`** function.  
You need to pass as argument a **`torch.device`** object.

A **`torch.device`** is an object representing the device on which a torch.tensor is or will be allocated.

_Note : If you don't have Cuda on the machine, the following examples won't work_

In [268]:
cpu = torch.device('cpu')
cuda_0 = torch.device('cuda:0')

x = x.to(cpu)
print(x.device)
x = x.to(cuda_0)
print(x.device)

cpu


AssertionError: Torch not compiled with CUDA enabled

It is flexible since you can check if cuda exists only once in your code

In [269]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
x = x.to(device)  # We don't need to worry anymore about whether cuda is available or not
print(x.device)

cpu


### `Tensor.cuda` and `Tensor.cpu`

When you know in advance what device you want to move to, you can use the `Tensor.cuda()` and `Tensor.cpu()` functions.


In [270]:
x = torch.Tensor([[1,2,3], [4,5,6]])
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [271]:
x.cuda()
print(x.device)
x = x.cuda()
print(x.device)
x = x.cuda(1)
print(x.device)
x = x.cpu()
print(x.device)

AssertionError: Torch not compiled with CUDA enabled

In [272]:
x = torch.Tensor([[1,2,3], [4,5,6]])

# This will generate an error since you cannot do operation on tensor that are not on the same device
x + x.cuda()

AssertionError: Torch not compiled with CUDA enabled

#### Write an if statement that moves x on gpu if cuda is available

In [273]:
# YOUR TURN

These kinds of if statements used to be all over the place in people's code.  
Now, the more flexible `Tensor.to(...)` function is available and should be used preferably.

### Timing GPU

How much faster is GPU ?  See for yourself ...

In [274]:
A = torch.rand(100, 1000, 1000)
B = A.cuda()
A.size()

AssertionError: Torch not compiled with CUDA enabled

In [278]:
%timeit -n 3 torch.bmm(A, A)

1.28 s ± 169 ms per loop (mean ± std. dev. of 7 runs, 3 loops each)


In [276]:
%timeit -n 30 torch.bmm(B, B)

# 解释：
# %timeit：测量 torch.bmm(A, A) 代码的执行时间。
# -n 3：指定 torch.bmm(A, A) 会执行 3 次，以便进行多次测量并计算平均时间和标准差。这里的 3 表示代码运行 3 次，timeit 会执行多次以便得出稳定的平均运行时间。
# torch.bmm(A, A)：torch.bmm 是 批量矩阵乘法（batch matrix multiplication）的函数。它用于执行两个 3D 张量的批量矩阵乘法，假设 A 是一个 3D 张量，形状为 [batch_size, n, m]，则 torch.bmm(A, A) 会执行批量矩阵乘法，结果张量的形状为 [batch_size, n, n]。
# 解释 torch.bmm：
# torch.bmm(A, A) 的作用是对张量 A 中的每一对矩阵执行矩阵乘法。对于批量大小为 batch_size 的张量 A，torch.bmm(A, A) 将为每对矩阵执行乘法，生成批量矩阵乘法的结果。
# 
# 假设：
# 
# A 的形状是 [batch_size, n, m]，那么 torch.bmm(A, A) 将执行批量的矩阵乘法，产生一个形状为 [batch_size, n, n] 的结果。

RuntimeError: batch1 must be a 3D tensor

___

<!--NAVIGATION-->
# | Basics | [Autograd >](2-Autograd.ipynb)